const order = [
  {
    id: "HD2023701",
    from: "456 Lê Văn Quới, P. Bình Trị Đông, Q. Bình Tân TP.HCM",
    to: "Số 12 Nguyễn Văn Bảo P.4, Q.Gò Vấp, TP.HCM",
    note: "Trường Đại học Công Nghiệp TPHCM",
    peopleSend: "Nguyễn Văn Bình",
    phoneSend: "0909152365",
    peopleReceive: "Nguyễn Văn An",
    phoneReceive: "0794812125",
    shipper: {
      id: "SHIP00001",
      name: "Lê Tấn Tài",
      numberTruck: "53-2D.14515",
    },
    distance: "50km",
    expectedTime: "3-5 ngày",
    price: 2500000,
    status: "Đã giao",
    reason: null,
    idCancel: null,
    review: {
      star: null,
      comment: null,
    },
  },
  {
    id: "HD2023003",
    from: "456 Lê Văn Quới, P. Bình Trị Đông, Q. Bình Tân TP.HCM",
    to: "Số 12 Nguyễn Văn Bảo P.4, Q.Gò Vấp, TP.HCM",
    note: "Trường Đại học Công Nghiệp TPHCM",
    peopleSend: "Nguyễn Văn Bình",
    phoneSend: "0909152365",
    peopleReceive: "Nguyễn Văn An",
    phoneReceive: "0794812125",
    shipper: {
      id: "SHP2310001",
      name: "Lê Tấn Tài",
      numberTruck: "53-2D.14515",
    },
    distance: "50km",
    expectedTime: "3-5 ngày",
    price: 2500000,
    status: "Đã giao",
    reason: null,
    idCancel: null,
    review: {
      star: 4,
      comment: "Giao hàng nhanh, tốt",
    },
  },
  {
    id: "HD2023004",
    from: "456 Lê Văn Quới, P. Bình Trị Đông, Q. Bình Tân TP.HCM",
    to: "Số 12 Nguyễn Văn Bảo P.4, Q.Gò Vấp, TP.HCM",
    note: "Trường Đại học Công Nghiệp TPHCM",
    peopleSend: "Nguyễn Văn Bình",
    phoneSend: "0909152365",
    peopleReceive: "Nguyễn Văn An",
    phoneReceive: "0794812125",
    shipper: {
      id: "SHP2310001",
      name: "Lê Tấn Tài",
      numberTruck: "53-2D.14515",
    },
    distance: "50km",
    expectedTime: "3-5 ngày",
    price: 2500000,
    status: "Đã hủy",
    reason:
      "Khách hàng đặt khối lượng hàng hóa lớn hơn so với trọng tải của xe",
    idCancel: "SHP2310001",
    review: {
      star: null,
      comment: null,
    },
  },
  {
    id: "HD2023005",
    from: "456 Lê Văn Quới, P. Bình Trị Đông, Q. Bình Tân TP.HCM",
    to: "Số 12 Nguyễn Văn Bảo P.4, Q.Gò Vấp, TP.HCM",
    note: "Trường Đại học Công Nghiệp TPHCM",
    peopleSend: "Nguyễn Văn Bình",
    phoneSend: "0909152365",
    peopleReceive: "Nguyễn Văn An",
    phoneReceive: "0794812125",
    shipper: {
      id: null,
      name: null,
      numberTruck: null,
    },
    distance: "50km",
    expectedTime: "3-5 ngày",
    price: 2500000,
    status: "Đã hủy",
    reason: "Shipper đến quá lâu",
    idCancel: "KH2023001",
    review: {
      star: null,
      comment: null,
    },
  },
];
export default order;
